export const STATUS_LOCKED = 'STATUS_LOCKED';
export const STATUS_UNLOCKED = 'STATUS_UNLOCKED';
export const STATUS_OWNED = 'STATUS_OWNED';
export const STATUS_ACED = 'STATUS_ACED';
export const STATUS_ALERTED = 'STATUS_ALERTED';
export const STATUS_FOCUSED = 'STATUS_FOCUSED';
