export const SWITCH_MAIN_TAB = 'SWITCH_MAIN_TAB';

export const LOAD_LANGS = 'LOAD_LANGS';

export const LOAD_SKILLS = 'LOAD_SKILLS';
export const HANDLE_SKILL_EVENT = 'HANDLE_SKILL_EVENT';
export const SWITCH_SKILL_TREE = 'SWITCH_SKILL_TREE';
export const RESPEC_SKILL_TREE = 'RESPEC_SKILL_TREE';

export const LOAD_PERKS = 'LOAD_PERKS';
export const HANDLE_PERK_EVENT = 'HANDLE_PERK_EVENT';
export const HANDLE_DECK_EVENT = 'HANDLE_DECK_EVENT';

export const LOAD_INFAMYTREE = 'LOAD_INFAMYTREE';
export const HANDLE_INFAMY_EVENT = 'HANDLE_INFAMY_EVENT';
